"""
SMT-LIB2 export: dumps the naive and structured solvers for every check
site to individual .smt2 files, so reviewers can inspect the actual
encoding independently of this tool's printed sat/unsat verdict.

Usage (called from pipeline.py / sweep_corpus.sh, not usually run directly):

    from smt2_export import export_program_smt2
    export_program_smt2(program, sync_results, wf_results, out_dir,
                         repo="asyncpg", source_file="pool.py")

Produces, per sync-object check:
    <out_dir>/<repo>__<file>__<object>__naive.smt2
    <out_dir>/<repo>__<file>__<object>__structured.smt2

and per wait_for site:
    <out_dir>/<repo>__<file>__waitfor_<coro>_L<line>__naive.smt2
    <out_dir>/<repo>__<file>__waitfor_<coro>_L<line>__structured.smt2

Each file is a self-contained SMT-LIB2 script (z3's `Solver.to_smt2()`
output, plus a `(check-sat)` command) that can be run standalone with any
SMT-LIB2-compliant solver, not just z3 -- e.g. `z3 file.smt2` or
`cvc5 file.smt2` should reproduce the same sat/unsat verdict this pipeline
printed.
"""

import os
import re


def _safe_component(s: str) -> str:
    """Turn a repo/file/object name into a filesystem-safe path component."""
    s = str(s)
    s = s.replace(os.sep, "_").replace("/", "_")
    s = re.sub(r"[^A-Za-z0-9._-]", "_", s)
    return s


def _write_smt2(solver, path, header_comment):
    """Write a solver's constraints as a standalone, runnable SMT-LIB2
    script: z3's to_smt2() already includes the assertions and a
    trailing (check-sat), so we just prepend a provenance comment."""
    smt2_text = solver.to_smt2()
    with open(path, "w") as f:
        f.write(f"; {header_comment}\n")
        f.write("; Generated by snf-pipeline (encoder.py) -- run with any\n")
        f.write("; SMT-LIB2-compliant solver, e.g. `z3 " + os.path.basename(path) + "`\n")
        f.write(smt2_text)
        if "(check-sat)" not in smt2_text:
            f.write("\n(check-sat)\n")


def export_program_smt2(program, sync_results, wf_results, out_dir,
                         repo="", source_file=""):
    """Write every naive/structured solver in sync_results (from
    encoder.check_all) and wf_results (from encoder.check_wait_for) to
    .smt2 files under out_dir. Returns the list of file paths written."""
    os.makedirs(out_dir, exist_ok=True)
    written = []

    repo_c = _safe_component(repo) if repo else ""
    file_c = _safe_component(source_file) if source_file else ""
    prefix_parts = [p for p in (repo_c, file_c) if p]
    prefix = "__".join(prefix_parts)

    for obj_name, r in sync_results.items():
        obj_c = _safe_component(obj_name)
        base = f"{prefix}__{obj_c}" if prefix else obj_c
        for variant in ("naive", "structured"):
            solver_key = f"solver_{variant}"
            if solver_key not in r:
                continue
            path = os.path.join(out_dir, f"{base}__{variant}.smt2")
            header = (f"{repo or '(no repo)'} :: {source_file or '(no file)'} :: "
                      f"{r.get('kind', '?')} '{obj_name}' :: {variant} encoding "
                      f"(verdict: {r.get(variant, '?')})")
            _write_smt2(r[solver_key], path, header)
            written.append(path)

    for r in wf_results:
        coro_c = _safe_component(r["coro"])
        base = f"{prefix}__waitfor_{coro_c}_L{r['line']}" if prefix else f"waitfor_{coro_c}_L{r['line']}"
        for variant in ("naive", "structured"):
            solver_key = f"solver_{variant}"
            if solver_key not in r:
                continue
            path = os.path.join(out_dir, f"{base}__{variant}.smt2")
            header = (f"{repo or '(no repo)'} :: {source_file or '(no file)'} :: "
                      f"wait_for at {r['coro']}:{r['line']} :: {variant} encoding "
                      f"(verdict: {r.get(variant, '?')})")
            _write_smt2(r[solver_key], path, header)
            written.append(path)

    return written